---
- name: remove_user
  hosts: pl_servers
  become: yes

  tasks:

  - name: Remove the user
    user:
      name: "{{ item }}"
      state: absent
      remove: yes
    with_items:
      - a.shevchuk
      - r.kozin
      - o.filiutsich
      - s.makarevich
      - e.rybak
      - s.ambroziak
