---
- name: add_user
  hosts: all
  become: yes

  tasks:

  - name: Add the user
    user:
      name: pavel.korzun
      shell: /bin/bash
      group: pavel.korzun
      append: yes

  - name: Add authorized keys
    authorized_key:
      user: pavel.korzun
      key: "{{ lookup('file', '/home/niksam/Documents/ansible/add_user/id_rsa.pub') }}"
